twig:
  form:
    resources:
        - 'SnowcapAdminBundle:Form:widgets.html.twig'
snowcap_im:
    formats:
        admin_thumb:
            thumbnail: 180x120>
            background: white
            gravity: center
            extent: 180x120
        admin_smallthumb:
            thumbnail: 50x30>
            background: transparent
            gravity: center
            extent: 50x30
