snowcap_admin_default_index:
    pattern: ""
    defaults: { _controller: SnowcapAdminBundle:Default:index }

# Content routes
snowcap_admin_content_index:
    pattern: /content/{code}
    defaults: { _controller: SnowcapAdminBundle:Content:index }

snowcap_admin_content_create:
    pattern: /content/{code}/create
    defaults: { _controller: SnowcapAdminBundle:Content:create }

snowcap_admin_content_update:
    pattern: /content/{code}/update/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:update }

snowcap_admin_content_delete:
    pattern: /content/{code}/delete/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:delete }

# Inline routes
snowcap_admin_inlinecontent_autocomplete:
    pattern: /inline/{code}/autocomplete/{input}
    defaults: { _controller: SnowcapAdminBundle:InlineContent:autocomplete }
snowcap_admin_inlinecontent_create:
    pattern: /inline/{code}/create
    defaults: { _controller: SnowcapAdminBundle:InlineContent:create }

# Default routes
snowcap_admin_markdown:
    pattern: /markdown
    defaults: { _controller: SnowcapAdminBundle:Default:markdown }