snowcap_admin_default_index:
    pattern: ""
    defaults: { _controller: SnowcapAdminBundle:Default:index }

# Content routes
snowcap_admin_content_index:
    pattern: /content/{code}
    defaults: { _controller: SnowcapAdminBundle:Content:index }

snowcap_admin_content_create:
    pattern: /content/{code}/create/{locale}
    defaults: { _controller: SnowcapAdminBundle:Content:create, locale: null }

snowcap_admin_content_update:
    pattern: /content/{code}/update/{id}/{locale}
    defaults: { _controller: SnowcapAdminBundle:Content:update, locale: null }

snowcap_admin_content_delete:
    pattern: /content/{code}/delete/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:delete }

# Inline routes
snowcap_admin_inlinecontent_autocomplete:
    pattern: /inline/{code}/autocomplete/{input}
    defaults: { _controller: SnowcapAdminBundle:InlineContent:autocomplete }
snowcap_admin_inlinecontent_create:
    pattern: /inline/{code}/create
    defaults: { _controller: SnowcapAdminBundle:InlineContent:create }

# Default routes
snowcap_admin_markdown:
    pattern: /markdown
    defaults: { _controller: SnowcapAdminBundle:Default:markdown }

# Wysiwyg routes
snowcap_admin_wysiwyg_browser:
    pattern: /wysiwyg/browser
    defaults: { _controller: SnowcapAdminBundle:Wysiwyg:browser }
snowcap_admin_wysiwyg_upload:
    pattern: /wysiwyg/upload
    defaults: { _controller: SnowcapAdminBundle:Wysiwyg:upload }
