snowcap_admin_default_index:
    pattern: ""
    defaults: { _controller: SnowcapAdminBundle:Default:index }

snowcap_admin_content_index:
    pattern: /content/{code}
    defaults: { _controller: SnowcapAdminBundle:Content:index }

snowcap_admin_content_create:
    pattern: /content/{code}/create
    defaults: { _controller: SnowcapAdminBundle:Content:create }

snowcap_admin_content_update:
    pattern: /content/{code}/update/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:update }
