snowcap_admin_default_index:
    pattern: ""
    defaults: { _controller: SnowcapAdminBundle:Default:index }

# Content routes
snowcap_admin_content_index:
    pattern: /content/{code}
    defaults: { _controller: SnowcapAdminBundle:Content:index }

snowcap_admin_content_create:
    pattern: /content/{code}/create
    defaults: { _controller: SnowcapAdminBundle:Content:create }

snowcap_admin_content_update:
    pattern: /content/{code}/update/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:update }

snowcap_admin_content_delete:
    pattern: /content/{code}/delete/{id}
    defaults: { _controller: SnowcapAdminBundle:Content:delete }

# Inline routes
snowcap_admin_inline_select:
    pattern: /inline/{code}/select}
    defaults: { _controller: SnowcapAdminBundle:Inline:select }
snowcap_admin_inline_create:
    pattern: /inline/{code}/create/{property}
    defaults: { _controller: SnowcapAdminBundle:Inline:create }
snowcap_admin_inline_preview:
    pattern: /inline/{code}/preview/{id}
    defaults: { _controller: SnowcapAdminBundle:Inline:preview }

# Default routes
snowcap_admin_markdown:
    pattern: /markdown
    defaults: { _controller: SnowcapAdminBundle:Default:markdown }