parameters:

services:
    # Main admin class
    snowcap_admin:
        class: Snowcap\AdminBundle\AdminManager

    # Base admin services
    snowcap_admin.admin_content:
        class: Snowcap\AdminBundle\Admin\ContentAdmin
        abstract: true
        calls:
            - [ setEntityManager, [@doctrine.orm.entity_manager] ]
            - [ setDatalistFactory, [@snowcap_admin.datalist_factory] ]
            - [ setFormFactory, [@form.factory] ]
            - [ setRoutingHelper, [@snowcap_admin.routing_helper_content] ]

    # Routing
    snowcap_admin.routing_loader:
        class: Snowcap\AdminBundle\Routing\Loader\AdminLoader
        arguments: [@snowcap_admin]
        tags:
            - { name: routing.loader }

    snowcap_admin.routing_helper_content:
        class: Snowcap\AdminBundle\Routing\Helper\ContentRoutingHelper
        arguments: [@router, "", ""]

    # Param converters
    snowcap_admin.param_converter:
        class: Snowcap\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [@snowcap_admin]
        tags:
            - { name: request.param_converter }

    # Subscriber for activating admin classes shortcuts
#    snowcap_admin.admin_subscriber:
#        class: Snowcap\AdminBundle\Listener\AdminSubscriber
#        arguments: [@snowcap_admin]
#        tags:
#            - { name: doctrine.event_subscriber}

    # Twig extensions
    snowcap_admin.twig_admin:
        class: Snowcap\AdminBundle\Twig\Extension\AdminExtension
        arguments: [@snowcap_admin, @snowcap_admin.routing_helper_content, @translator]
        tags:
            -  { name: twig.extension }

    snowcap_admin.twig_datalist:
        class: Snowcap\AdminBundle\Twig\Extension\DatalistExtension
        arguments: [@form.factory]
        calls:
            - [ setContainer, [@service_container]]
        tags:
            -  { name: twig.extension }

    # Form types
    snowcap_admin.form_type_slug:
        class: Snowcap\AdminBundle\Form\Type\SlugType
        tags:
            -  { name: form.type, alias: snowcap_admin_slug }

    snowcap_admin.form_type_markdown:
        class: Snowcap\AdminBundle\Form\Type\MarkdownType
        tags:
            -  { name: form.type, alias: snowcap_admin_markdown }

    snowcap_admin.form_type_wysiwyg:
        class: Snowcap\AdminBundle\Form\Type\WysiwygType
        tags:
            -  { name: form.type, alias: snowcap_admin_wysiwyg }

    snowcap_admin.form_type_entity:
        class: Snowcap\AdminBundle\Form\Type\EntityType
        arguments: [@snowcap_admin, @snowcap_admin.routing_helper_content]
        tags:
            - { name: form.type, alias: snowcap_admin_entity }

    snowcap_admin.form_type_autocomplete:
        class: Snowcap\AdminBundle\Form\Type\AutocompleteType
        arguments: [@snowcap_admin, @snowcap_admin.routing_helper_content]
        tags:
            -  { name: form.type, alias: snowcap_admin_autocomplete }

    # Datalists
    snowcap_admin.datalist_factory:
        class: Snowcap\AdminBundle\Datalist\DatalistFactory
        arguments: [@form.Factory]

    snowcap_admin.datalist_type.datalist:
        class: Snowcap\AdminBundle\Datalist\Type\DatalistType
        tags:
            - { name: snowcap_admin.datalist_type, alias: datalist }

    snowcap_admin.datalist_field_datetime:
        class: Snowcap\AdminBundle\Datalist\Field\Type\DateTimeFieldType
        tags:
            - { name: snowcap_admin.datalist_fieldtype, alias: datetime }

    snowcap_admin.datalist_field_heading:
        class: Snowcap\AdminBundle\Datalist\Field\Type\HeadingFieldType
        tags:
            - { name: snowcap_admin.datalist_fieldtype, alias: heading }

    snowcap_admin.datalist_field_image:
        class: Snowcap\AdminBundle\Datalist\Field\Type\ImageFieldType
        tags:
            - { name: snowcap_admin.datalist_fieldtype, alias: image }

    snowcap_admin.datalist_field_label:
        class: Snowcap\AdminBundle\Datalist\Field\Type\LabelFieldType
        tags:
            - { name: snowcap_admin.datalist_fieldtype, alias: label }

    snowcap_admin.datalist_field_image:
        class: Snowcap\AdminBundle\Datalist\Field\Type\TextFieldType
        tags:
            - { name: snowcap_admin.datalist_fieldtype, alias: text }

    snowcap_admin.datalist_filter_choice:
        class: Snowcap\AdminBundle\Datalist\Filter\Type\ChoiceFilterType
        tags:
            - { name: snowcap_admin.datalist_filtertype, alias: choice }

    snowcap_admin.datalist_filter_entity:
        class: Snowcap\AdminBundle\Datalist\Filter\Type\EntityFilterType
        tags:
            - { name: snowcap_admin.datalist_filtertype, alias: entity }

    snowcap_admin.datalist_filter_search:
        class: Snowcap\AdminBundle\Datalist\Filter\Type\SearchFilterType
        tags:
            - { name: snowcap_admin.datalist_filtertype, alias: search }

    snowcap_admin.datalist_action_simple:
        class: Snowcap\AdminBundle\Datalist\Action\Type\SimpleActionType
        arguments: [@router]
        tags:
            - { name: snowcap_admin.datalist_actiontype, alias: simple }

    snowcap_admin.datalist_action_content_admin:
        class: Snowcap\AdminBundle\Datalist\Action\Type\ContentAdminActionType
        arguments: [@snowcap_admin.routing_helper_content]
        tags:
            - { name: snowcap_admin.datalist_actiontype, alias: content_admin }

    # Admin logger
    snowcap_admin.logger:
        class: Snowcap\AdminBundle\Logger\Logger
        arguments: [@doctrine, @security.context]