parameters:
  sections: ~
  bundle: ~
  translation_catalogues: ~

services:
  snowcap_admin:
    class: Snowcap\AdminBundle\Environment
    arguments: [%sections%]
    calls:
        - [setContainer, [ @service_container ]]
        - [setBundle, [ %bundle% ]]
        - [setTranslationCatalogues, [ %translation_catalogues% ]]

  # subscriber for activating admin classes shortcuts
  snowcap_admin.admin_subscriber:
    class: Snowcap\AdminBundle\Listener\AdminSubscriber
    arguments: [@snowcap_admin]
    tags:
      - { name: doctrine.event_subscriber}

  # Twig extensions
  snowcap_admin.twig:
    class: Snowcap\AdminBundle\Twig\Extension\AdminExtension
    arguments: [@snowcap_admin ]
    tags:
      -  { name: twig.extension }

  # Forms
  snowcap_admin.slug:
    class: Snowcap\AdminBundle\Form\Type\SlugType
    tags:
      -  { name: form.type, alias: slug }

  snowcap_admin.inline:
    class: Snowcap\AdminBundle\Form\Type\InlineType
    arguments: [@snowcap_admin]
    tags:
      -  { name: form.type, alias: snowcap_admin_inline }

  snowcap_admin.translatable_entity:
    class: Snowcap\AdminBundle\Form\Type\TranslatableEntityType
    arguments: [@doctrine, @snowcap_admin]
    tags:
      -  { name: form.type, alias: snowcap_admin_translatable_entity }

  snowcap_admin.markdown:
    class: Snowcap\AdminBundle\Form\Type\MarkdownType
    tags:
      -  { name: form.type, alias: markdown }

  snowcap_admin.wysiwyg:
    class: Snowcap\AdminBundle\Form\Type\WysiwygType
    arguments: [@router]
    tags:
      -  { name: form.type, alias: wysiwyg }

  snowcap_admin.content_search:
    class: Snowcap\AdminBundle\Form\Type\ContentSearchType
    tags:
      - { name: form.type, alias: snowcap_admin_content_search }

  snowcap_admin.content_filter:
    class: Snowcap\AdminBundle\Form\Type\ContentFilterType
    tags:
      - { name: form.type, alias: snowcap_admin_content_filter }

  #Datalists
  snowcap_admin.datalist_factory:
    class: Snowcap\AdminBundle\Datalist\DatalistFactory

  snowcap_admin.datalist_view.grid:
    class: Snowcap\AdminBundle\Datalist\View\GridView
    tags:
      - { name: snowcap_admin.datalist_view, alias: grid }

  snowcap_admin.datalist_view.thumbnail:
    class: Snowcap\AdminBundle\Datalist\View\ThumbnailView
    tags:
      - { name: snowcap_admin.datalist_view, alias: thumbnail }

  snowcap_admin.logger:
    class: Snowcap\AdminBundle\Logger\Logger
    arguments: [@doctrine, @security.context]