parameters:
  sections: ~

services:
  snowcap_admin:
    class: Snowcap\AdminBundle\Environment
    arguments: [%sections%]
    calls:
        - [setContainer, [ @service_container ]]


    

  snowcap_admin.twig:
    class: Snowcap\AdminBundle\Twig\Extension\AdminExtension
    tags:
      -  { name: twig.extension }

  snowcap_admin.slug:
    class: Snowcap\AdminBundle\Form\Type\SlugType
    tags:
      -  { name: form.type, alias: slug }

  snowcap_admin.inline:
    class: Snowcap\AdminBundle\Form\Type\InlineType
    arguments: [@snowcap_admin]
    tags:
      -  { name: form.type, alias: snowcap_admin_inline }

  snowcap_admin.markdown:
    class: Snowcap\AdminBundle\Form\Type\MarkdownType
    tags:
      -  { name: form.type, alias: markdown }

  snowcap_admin.form.collection:
    class: Snowcap\AdminBundle\Form\Extension\CollectionTypeExtension
    tags:
      -  { name: form.type_extension, alias: collection }

  #Datalists
  snowcap_admin.datalist_factory:
    class: Snowcap\AdminBundle\Datalist\DatalistFactory
    arguments: [[]]

  snowcap_admin.datalist_view.grid:
    class: Snowcap\AdminBundle\Datalist\View\GridView
    tags:
      - { name: snowcap_admin.datalist_view, alias: grid }

  snowcap_admin.datalist_view.thumbnail:
    class: Snowcap\AdminBundle\Datalist\View\ThumbnailView
    tags:
      - { name: snowcap_admin.datalist_view, alias: thumbnail }